### ISSUE TITLE
Flickering/empty select options in Livewire 1.3

### ISSUE THREAD

**Issue by colinmac17** [livewire/livewire#1246]
### Description

Complete video overview of behavior from 1.2 -> 1.3:
https://www.loom.com/share/dd5cd2c6d0bc4b658a37492f8538861a

Models binded to select elements seem to start as blank and when changing options there is sometimes flickering where you briefly see the selected option and then it goes blank again. Note that this is all on the front end as far as I can tell. On the backend the data is being updated correctly, but from a UI/UX standpoint this is not the best look for the user because they do not know what that select is currently set to.

As mentioned in the video, I could totally be doing something wrong here with how I'm binding this.

Here is my code: https://gist.github.com/colinmac17/2afe214019a2d5f6bdf751a0b43d4a70

### Steps to reproduce

1. Create a select element using wire:model
2. Bind it to a Livewire component
3. See if the field starts out with no option showing (select looks blank) and look for flickering when changing options

**Context**
- Livewire version: [e.g. 1.3.1]
- Laravel version: [e.g. 7.19.0]
- Browser: [Chrome]

**Comment by ATholin** [comment]
It seems like the 1.3.0 update explicitly reset the `<select>` index to fix a few small bugs. However, the `selectedIndex` is reset to `-1`, which indicates that [no element is selected](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedIndex). Maybe this should be set to `0` instead?

**Comment by Dimonka2** [comment]
Or at least to take in account empty value option like:
`<option value="" selected="">{Please select}</option>`
Even if input explicitly rendered as "selected" it getting set to empty if the model variable is `null`. 

Even worse situation is if model is linked to an array. For example if input `wire:model="inputs.0"` and `$inputs = []` then this input may get any random values from other fields depending on those fields visibility. I would prefer in this case that Livewire will look in the element property and consider the html rendered inputs as default. In order not to have this issue array needs to be populated with null values for all linked models, like `$inputs = [0=>null]`. And after we are at the issue of topic stater :-)

**Comment by ahinkle** [comment]
I'm also experiencing this bug. I've noticed it only happens when I have multiple select fields on the page. 

When I only have one select field on the page there doesn't appear to be any issues.

**Comment by jakjr** [comment]
Maybe this is releated with this issue:
https://github.com/livewire/livewire/issues/826

**Comment by colinmac17** [comment]
@jakjr look like that was the issue Caleb fixed in 1.3.1? This is different. I am seeing empty options when I have a first option that is empty. This happened when going from 1.2 to 1.3 for me.

**Comment by itepifanio** [comment]
@colinmac17 same happened here when I updated from 1.2 to 1.3. In my case, I have a  global select component and the update broke my entire system, so I rolled back the version for now.

**Comment by ninthspace** [comment]
@itepifanio @colinmac17 Selects are all weird for me with 1.3, but that might be due to my code compensating for issues with previous versions, so I'm still using 1.2. I am deliberately setting an option as "selected" if one is should be selected at the time of initial rendering. Maybe I shouldn't? With 1.2, I'm doing this to recompute selects, which fixes blank selects but this doesn't work with 1.3.

```javascript
    document.addEventListener('livewire:load', function (event) {
        window.livewire.hook('afterDomUpdate', () => {
            const selectBoxes = document.querySelectorAll('.some-class select');
            selectBoxes.forEach(function (s) {
                const selectedOption = s.querySelector('option[selected]');
                if (selectedOption) {
                    s.value = selectedOption.value;
                }
            });
        });
    });
```

**Comment by uteq** [comment]
I am experiencing the same problem. What I did to fix this (for now) is use wire:ignore
https://laravel-livewire.com/docs/alpine-js (Ignoring DOM-changes (using wire:ignore))

```blade
<div wire:ignore>
    <select name="option_name" wire:model="option_name">
         <option...
    </select>
</div>
```

This actually just completely disables Livewire for the select option.
After that use this example to update the wire:model:

https://laravel-livewire.com/docs/third-party-libraries

```blade
@push('scripts')
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').on('change', function (e) {
            @this.set('option_name', e.target.value);
        });
    });
</script>
@endpush
```

This is not the best solution, but might help people who really need this to work.

**Comment by calebporzio** [comment]
Ok, I reverted the .selectedIndex change from 1.3.

Pull down 1.3.2 and PLEASE ping me if these problems still persist.

There was another change I introduced that could affect this, so that's entirely possible.

Thanks, everyone!

**Comment by ahinkle** [comment]
Hey Caleb,

I'm still having some issues with it flashing and not presenting the options in specified (alphabetical) order using a simple US state dropdown:

![Jul-18-2020 22-02-49](https://user-images.githubusercontent.com/17038330/87866102-fbef2600-c942-11ea-91e6-bf551266e5bd.gif)


```php
class StateComponent extends Component
{
    public $state;
    public $stateOptions = [
        'AK' => 'Alaska',
        'AL' => 'Alabama',
        'AR' => 'Arkansas',
        'AZ' => 'Arizona',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DC' => 'District of Columbia',
        'DE' => 'Delaware',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'HI' => 'Hawaii',
        'IA' => 'Iowa',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'MA' => 'Massachusetts',
        'MD' => 'Maryland',
        'ME' => 'Maine',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MO' => 'Missouri',
        'MS' => 'Mississippi',
        'MT' => 'Montana',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'NE' => 'Nebraska',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NV' => 'Nevada',
        'NY' => 'New York',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PA' => 'Pennsylvania',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VA' => 'Virginia',
        'VT' => 'Vermont',
        'WA' => 'Washington',
        'WI' => 'Wisconsin',
        'WV' => 'West Virginia',
        'WY' => 'Wyoming',
    ];

    public function render()
    {
        return view('livewire.state-component');
    }
}
```

Blade:
```php
<div>
    <select wire:model="state">
        <option value="">Select State</option>
        @foreach ($stateOptions as $abbr => $state)
            <option value="{{ $abbr }}">{{ $state }}</option>
        @endforeach
    </select>
</div>
```

**Comment by lucasromanojf** [comment]
@calebporzio unfortunately still happens for me on 1.3.2. After a livewire DOM update, the default option for selects turns into an empty one instead of the explicit empty option.

**Comment by colinmac17** [comment]
I see some are still having issues but fwiw, I am no longer seeing the issue any longer with no code changes.

**Comment by lucasromanojf** [comment]
I've found out the issue in my case. It was strange that it was only happening in production. Incredibly the issue was related to Cloudflare caching. Changing my Cloudflare caching config to Development Mode solved it.

**Comment by colinmac17** [comment]
@lucasromanojf glad to hear it!

**Comment by krizzdev** [comment]
I have the same issue like ahinkle. (Livewire 1.3.2) .
The default option is set correclty now, but when I select another one (which is set on the backend side) The selected option turns blank. After selecting another one it works.

**Comment by lucasromanojf** [comment]
> I have the same issue like ahinkle. (Livewire 1.3.2) .
> The default option is set correclty now, but when I select another one (which is set on the backend side) The selected option turns blank. After selecting another one it works.

Hey, I was having the exact same issue. Exactly the same. I don't know if you are using Cloudflare, but after I disabled minifying of HTML, js and css files and purged cache in my Cloudflare, this issue stopped happening for me.

**Comment by krizzdev** [comment]
Thanks lucasromanojf . Unfortunately thats not my case. It happens already on my local machine. (without cloudflare)

**Comment by lucasromanojf** [comment]
@krizzdev try adding a different wire:key for each option, including the empty one if it exists. Also try adding a wire:key to your select. Just to see if something changes.

**Comment by krizzdev** [comment]
@lucasromanojf awesome thanks, totally forgot about the DOM diffing issues https://laravel-livewire.com/docs/troubleshooting
works now . TY :pray:

**Comment by lucasromanojf** [comment]
@krizzdev cool! Glad to hear that! :)

**Comment by calebporzio** [comment]
Closing due to inactivity.

**Comment by stuartcoxdesign** [comment]
had the same issue . 
Adding `wire:key` fixed the issue

**Comment by mayanksdudakiya** [comment]
@calebporzio I am having the same issue with the `"livewire/livewire": "2.5"`.  

1. I have a multi-select dropdown filter. 

```
<x-select class="h-20 multiselect" label="Website Tag" wire:key="filter-tags" wire:model.debounce.500ms="filters.tag" multiple>
    <option value="">All Tags</option>
    @foreach ($tags as $id => $tag_name)
        <option value="{{ $id }}">{{ $tag_name }}</option>
    @endforeach
</x-select>
```

2. So when I select the first default option "--Select--", it still shows me an array with:

```
"tag" => array:1 [▼
    0 => "All Tags"
 ]
```
3. Due to this I need to add more code to check. 

Hope this information is helpful to you to understand my query. Thanks :)

**Comment by kevindaus** [comment]
> @calebporzio I am having the same issue with the `"livewire/livewire": "2.5"`.
> 
> 1. I have a multi-select dropdown filter.
> 
> ```
> <x-select class="h-20 multiselect" label="Website Tag" wire:key="filter-tags" wire:model.debounce.500ms="filters.tag" multiple>
>     <option value="">All Tags</option>
>     @foreach ($tags as $id => $tag_name)
>         <option value="{{ $id }}">{{ $tag_name }}</option>
>     @endforeach
> </x-select>
> ```
> 
> 2. So when I select the first default option "--Select--", it still shows me an array with:
> 
> ```
> "tag" => array:1 [▼
>     0 => "All Tags"
>  ]
> ```
> 
> 3. Due to this I need to add more code to check.
> 
> Hope this information is helpful to you to understand my query. Thanks :)




try adding the wire:key 

```
<x-select class="h-20 multiselect" label="Website Tag" wire:key="filter-tags" wire:model.debounce.500ms="filters.tag" multiple>
    <option value="">All Tags</option>
    @foreach ($tags as $id => $tag_name)
        <option wire:key="{{ $loop->index }}" value="{{ $id }}">{{ $tag_name }}</option>
    @endforeach
</x-select>
```

Refer to https://laravel-livewire.com/docs/2.x/troubleshooting#dom-diffing-symptoms
