### ISSUE TITLE
Pagination display error

### ISSUE THREAD

**Issue by nguyentranchung** [livewire/livewire#1536]
### Steps to reproduce
![livewire bug 1](https://user-images.githubusercontent.com/9611224/92830436-44d9cd00-f410-11ea-8395-527d258f343c.gif)

![image](https://user-images.githubusercontent.com/9611224/92830705-8b2f2c00-f410-11ea-8f2c-fc2bdd93207b.png)

**Context**
- Livewire version: 2.x
- Laravel version: 7.x
- Browser: Chrome

**Comment by iksaku** [comment]
I'm experiencing the same display issue with pagination links

![image](https://user-images.githubusercontent.com/4632429/92974986-fdbdfd00-f44c-11ea-93aa-08ff9d56359d.png)

**Comment by calebporzio** [comment]
Ok bootstrap pagination is now fixed in v2.1.1

Re-open if this is not the case for you

Thanks!

**Comment by iksaku** [comment]
My issue was with the Tailwind one, but was fixed as well :+1:

**Comment by nguyentranchung** [comment]
@calebporzio 
![image](https://user-images.githubusercontent.com/9611224/92997125-dbf76f80-f54b-11ea-86fa-0b31445a9aa3.png)
![image](https://user-images.githubusercontent.com/9611224/92997155-1a8d2a00-f54c-11ea-9c21-c8aba263d968.png)
This error still appears

**Comment by nguyentranchung** [comment]
![image](https://user-images.githubusercontent.com/9611224/92997393-fa5e6a80-f54d-11ea-902c-fdff6816072b.png)

because render has span tag

**Comment by nguyentranchung** [comment]
![image](https://user-images.githubusercontent.com/9611224/92997455-5e812e80-f54e-11ea-89fa-05852a4bd983.png)

**Comment by nguyentranchung** [comment]
@calebporzio 
```blade
<div>
    @foreach ($posts as $post)
        <h1 wire:key="post-{{ $post->id }}">{{ $post->title }}</h1>
    @endforeach

    {{ $posts->links() }}
</div>
```
When testing pagination, you can try rendering both above and below, like: 
```blade
<div>
    {{ $posts->links() }}

    @foreach ($posts as $post)
        <h1 wire:key="post-{{ $post->id }}">{{ $post->title }}</h1>
    @endforeach

    {{ $posts->links() }}
</div>
```
