### ISSUE TITLE
"Unable to find component" on sub-domain

### ISSUE THREAD

**Issue by NT-daviddefoe** [livewire/livewire#165]
**Describe the bug**
I created a Livewire component on my local machine.  When I uploaded the code to my testing server it was showing the component @livewire as a text string in the browser (@livewire('inventory.inventory-pricing', $vehicle->prices, $vehicle->id, $vehicle->vin)).

I then made a very simple component and uploaded to the test server (test.domain.com) and getting "Unable to find component" error.

**To Reproduce**
1. run: php artisan make:livewire livewirejunk
2. In web.php add: Route::view('/livewire', 'livewire');
3. Source of livewire.blade.php:
```
@extends('layouts.app')

@section('headers')

<style>
.fixed-sn main {
    margin-left: 2% !important;
    margin-right: 2% !important;
}
</style>
@endsection

@section('content')
    <h1 class="text-center">Livewire Test!</h1>

    <div>
        @livewire('livewirejunk')
    </div>
@endsection

@section('scripts')
@livewireAssets
@endsection
```

4. Source of livewire\livewirejunk.blade.php:
```
<div>
    {{-- Care about people's approval and you will be their prisoner. --}}
    <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat unde repellat ea incidunt. Quos sequi aspernatur delectus vero iste, ut voluptates minima voluptatibus placeat, dolore doloribus iure expedita quia assumenda!
    </div>
</div>
```

5. Source of App\Http\Livewire\livewirejunk.php:
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Livewirejunk extends Component
{
    public function render()
    {
        return view('livewire.livewirejunk');
    }
}
```

**Expected Result**
![image](https://user-images.githubusercontent.com/47991824/63052220-c88f5600-beac-11e9-8d62-f00832260de6.png)

**Error**
"Unable to find component: [livewirejunk] (View: /var/www/html/projectfolder/resources/views/livewire.blade.php)"

**Test Server**
 - Ubuntu 18.04.6 LTS
 - Server version: Apache/2.4.18 (Ubuntu)
 - Node v4.2.6
 - Laravel v5.8.32

**Comment by lalov** [comment]
Have you tried to rediscover the components? It helped me: 

php artisan livewire:discover

**Comment by intellow** [comment]
@lalov that command fixed my problem. Thanks!

**Comment by cosmicvibes** [comment]
This just saved me, thank you! This needs to be in the docs. And perhaps the exception could be captured and a helpful message presented to the user?

**Comment by faustbrian** [comment]
Someone could probably make an [ignition solution](https://flareapp.io/docs/solutions/adding-custom-solutions) for this so you could run `livewire:discover` if a Livewire component can't be found.

This solution could also use the levenshtein algorithm to check if the component name is a typo or if it is actually missing.

**Comment by calebporzio** [comment]
There are 2 things that should be done to make this better:  
1) Auto-regenerate the manifest file if a component is not found
2) Document that `artisan livewire:discover` command

**Comment by intellow** [comment]
> There are 2 things that should be done to make this better:
> 
> 1. Auto-regenerate the manifest file if a component is not found
> 2. Document that `artisan livewire:discover` command

If the auto-regeneration is implemented, is there any need to add that command to the docs? I can't think of a situation where you'd need to run that command manually if the component isn't found, Livewire automatically runs the discover command, and still can't find it.

**Comment by calebporzio** [comment]
Yeah, you're probably right @intellow - good point.

**Comment by intellow** [comment]
@calebporzio I can work on the PR. 😄 I've been looking for something else to help out with.

**Comment by calebporzio** [comment]
Awesome, thanks @intellow !

**Comment by lancepioch** [comment]
Somewhat related to #252 and #389

**Comment by lancepioch** [comment]
@NT-daviddefoe @intellow Is this issue resolved now that #429 is merged?

**Comment by intellow** [comment]
Yeah this can be closed.

**Comment by lancepioch** [comment]
@NT-daviddefoe This appears to be resolved now, let us know if that's not the case.

**Comment by osbre** [comment]
Problem:

`php artisan livewire:make TableComponent`

Solution:

`php artisan livewire:make table`

**Comment by luisneyker** [comment]
hello in my case that command did not solve the problem, something else I should check to solve it

**Comment by IVNtech** [comment]
am on the same thing, my components that are inside a folder inside Livewire like this example Livewire=>Profile=>comp.php
cant be found because is inside a subfolder... how to solve that?... why I don't find it??

**Comment by TCrown001** [comment]
Is still bringing the same error after running php artisan livewire:discover
