### ISSUE TITLE
Vue component disappearing after rerender

### ISSUE THREAD

**Issue by faustbrian** [livewire/livewire#388]
I am currently working on a component that lets the user manage their subscription to subscribe, update, resume and cancel. There is a single Vue component included in the Livewire component and a toggle to switch between billing intervals. The Vue component is rendered initially but consecutive renders happen without that component.

**Initial Render**
<img width="694" alt="Screenshot 2019-12-03 at 7 07 13" src="https://user-images.githubusercontent.com/22145591/70022146-cd7f2f00-159b-11ea-9d60-55f7ba63a1d4.png">

**After Switching Intervals and Rerendering**
<img width="699" alt="Screenshot 2019-12-03 at 7 07 18" src="https://user-images.githubusercontent.com/22145591/70022144-cd7f2f00-159b-11ea-87c2-d5a5c4cf8a30.png">

**Vue Component**
```vue
<template>
    <div>
        <button class="btn-primary text-sm" @click="redirectToCheckout">Subscribe</button>
    </div>
</template>

<script>
import axios from "axios";

export default {
    props: ["planId"],
    methods: {
        async redirectToCheckout() {
            const { data } = await axios.get(`/stripe/${this.planId}`);

            Stripe(window.App.stripeKey).redirectToCheckout({
                sessionId: data.sessionId
            });
        }
    }
};
</script>
```

I have two possible solutions in mind but I'm not sure if either of them is the best solution possible in the context of Livewire.

1. Render all plans at once and toggle them only in the UI instead of the actual list of plans in the backend which forces a rerender. Haven't tested this and suspect it will cause the same issue.
2. Inline the JavaScript bit of the Vue component into the Livewire component. The issue with this is that I am unable to figure out how to trigger the JavaScript bit after the checkout session ID would be created via PHP.

For solution 2, is there any way to call a JavaScript function from inside the Livewire component so that I could execute the Stripe redirect?

**Comment by faustbrian** [comment]
I eventually settled with the below as it feels the least hacky. @calebporzio would that be the recommended way of triggering some JavaScript from within the PHP portion of the component?

```php
<?php

namespace App\Http\Livewire;

use App\Plan;
use App\Services\Stripe;
use Livewire\Component;

class Subscribe extends Component
{
    public $interval = 'monthly';

    public $checkoutSessionId;

    public function changeInterval(string $interval): void
    {
        $this->interval = $interval;
    }

    public function redirectToCheckout(string $planId): void
    {
        $this->checkoutSessionId = resolve(Stripe::class)->createSession(team(), Plan::findOrFail($planId))->id;

        $this->emit('redirectToCheckout');
    }

    public function render()
    {
        return view('livewire.subscribe', [
            'plans' => Plan::where('interval', $this->interval)->get(),
        ]);
    }
}

```

```blade
@push('scripts')
    <script type="text/javascript">
        // Uncaught TypeError: Cannot read property 'find' of undefined
		// window.livewire is undefined until that listener is triggered
		// so we need to listen for it before we register our listener.
        document.addEventListener('livewire:available', function () {
            @this.on('redirectToCheckout', () => {
                Stripe(window.App.stripeKey).redirectToCheckout({
                    sessionId: @this.get('checkoutSessionId')
                });
            })
        });
    </script>
@endpush
```

As commented above in the JavaScript code, the `window.livewire` variable seems to be unavailable before components are rendered. I would've expected that value to be defined if you register `@livewireAssets` before `@stack('scripts')` but due to the fact that it uses an event listener it seems to be registered too late, thus needing that work around with the listener inside the component if you try to access it too early.

**Comment by faustbrian** [comment]
Just encountered this again with another component that uses https://stripe.com/en-fi/payments/elements. Initially the component renders fine but when the user enters their name and triggers a re-render of the Livewire component the Stripe Element disappears.

```blade
<div>
    @component('components.grid')
        @slot('title')
            Update Billing Method
        @endslot

        <form class="spaced-y-4" role="form">
            @include('shared.flash')

            @if($this->team->card_last_four)
                <div class="alert-info">
                    Your current card number is <strong>************{{ $this->team->card_last_four }}</strong>.
                </div>
            @endif

            @if($this->cardErrors)
                <div class="alert-danger">
                    {{ $this->cardErrors }}
                </div>
            @endif

            <label class="block">
                <span class="form-label">Cardholder's Name</span>

                <input type="text" class="form-input" wire:model="cardHolder">
            </label>

            <label class="block">
                <span class="form-label">Card</span>

                <div id="payment-card-element"></div>
            </label>

            <div class="form-buttons">
                <button type="button" class="transition-all btn-primary" wire:click="$emit('handleCardSetup')">
                    Update
                </button>
            </div>
        </form>
    @endcomponent
</div>

@push('scripts')
    <script src="https://js.stripe.com/v3/"></script>

    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', () => {
            const stripe = Stripe("{{ config('cashier.key') }}");

            if (!stripe) {
                throw new Error("Invalid Stripe Key/Secret");
            }

            const cardElement = stripe.elements().create("card", {
                hidePostalCode: true,
                style: {
                    base: {
                        color: "#1a202c",
                        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                        fontSize: "16px",
                        fontSmoothing: 'antialiased',
                        "::placeholder": {
                            color: "#cbd5e0"
                        }
                    },
                    invalid: {
                        color: '#ff2d20',
                        iconColor: '#ff2d20'
                    }
                }
            });

            cardElement.mount("#payment-card-element");

            @this.on('handleCardSetup', () => {
                stripe.handleCardSetup('{{ $this->stripeToken }}', cardElement, {
                    payment_method_data: {
                        billing_details: {
                            name: @this.get('cardHolder')
                        }
                    }
                }).then(response => {
                    if (response.error) {
                        console.log(response.error.message);
                        return;
                    }

                    @this.call('updateDefaultPaymentMethod', response.setupIntent.payment_method)
                });
            });
        })
    </script>
@endpush
```

<img width="870" alt="Screenshot 2020-01-03 at 6 54 35" src="https://user-images.githubusercontent.com/22145591/71707920-21c53b00-2df6-11ea-8aba-91e7d33db437.png">

<img width="880" alt="Screenshot 2020-01-03 at 6 54 40" src="https://user-images.githubusercontent.com/22145591/71707919-21c53b00-2df6-11ea-95b3-8094e5ff1c89.png">

**Comment by kevindierkx** [comment]
Same here with a google places autocomplete component. This started after upgrading from `livewire/livewire:^0.3.16`.

Running `window.livewire.rescan()` doesn't seem to affect this. @calebporzio do you have any suggestions where this might be broken?

**Comment by calebporzio** [comment]
@faustbrian,

Sorry about that. You need to add a `wire:ignore`. This should fix the issue:
`<div id="payment-card-element" wire:ignore></div>`

If that doesn't work, you might have to add the wire:ignore to the parent element instead.

Hope that helps.

**Comment by calebporzio** [comment]
@kevindierkx, `wire:ignore` is the solution to most of these problems. Basically, if a third-party JS library changes DOM in the component, Livewire will overwrite it on the next update with what it gets from the server. To prevent this, you can add `wire:ignore` OR `wire:ignore.self` to an element to tell Livewire to ignore DOM changes within it.

Make sense?

**Comment by faustbrian** [comment]
> @faustbrian,
> 
> Sorry about that. You need to add a `wire:ignore`. This should fix the issue:
> `<div id="payment-card-element" wire:ignore></div>`
> 
> If that doesn't work, you might have to add the wire:ignore to the parent element instead.
> 
> Hope that helps.

Totally forgot about `wire:ignore`, will give it a try when I get a chance.

**Comment by jgile** [comment]
Vue components still disappear in v0.7.2.  wire:ignore does not fix the problem.

**Comment by calebporzio** [comment]
@jgile Sorry about that. Looks like I did break Vue support along the way.

Fixed and tagged release: v0.7.3

**Comment by viaativaweb** [comment]
Hello, I installed livewire today, wire:ignore is not working anyome :( please fix

**Comment by viaativaweb** [comment]
it worked after I added `wire:key="unique_identifier"`

**Comment by Keyaku** [comment]
I'm sorry for bringing up a nearly 3-old issue, but I'm having the same trouble.
Using v2.3.8, I need to update a livewire <input> value from a Vue component; the issue comes up right after the value is updated, where all rendered components (not just Vue's) disappear. This is very frustrating, and none of the solutions in this thread seem tobe of help.
