### ISSUE TITLE
Data binding input lose focus after the first request

### ISSUE THREAD

**Issue by samoraa** [livewire/livewire#775]
**Describe the bug**
Input with `wire:model` lose focus after the first request was sent

**Expected behavior**
Input should focus until I blur or click away

**GIFs**
![capture](https://user-images.githubusercontent.com/53637476/77775683-db474b80-7087-11ea-9a1d-e8ef7550b124.gif)

**Additional context**
This issue however, solved if I place the input one level after the root `<div>`

```
<div>
    <h1 class="mb-8 font-bold text-3xl">Users</h1>

    <input wire:model="search" type="text"
        class="py-2 px-4 w-64 rounded shadow focus:shadow-outline focus:outline-none" placeholder="Search.."
        autocomplete="off">
</div>
```

Worked!

```
<div>
    <h1 class="mb-8 font-bold text-3xl">Users</h1>

    <div class="mb-6 flex justify-between items-center">
        <div class="flex items-center">
            <input wire:model="search" type="text"
                class="py-2 px-4 w-64 rounded shadow focus:shadow-outline focus:outline-none" placeholder="Search.."
                autocomplete="off">
        </div>
    </div>
</div>
```

Not worked :thinking:

Any help would be appreciated. Thanks.

**Comment by unpana** [comment]
I am having the same issue, likely caused by a conflict with Vue.

In my case, I moved the Livewire component outside of my Vue DOM element (i.e. `#app`) and the issue was solved. It would be good if they could play nice with each other, though.

**Comment by samoraa** [comment]
You're right @unpana, removing the Vue DOM element solves the problem.

But strangely it does work if I put the input one level after the root `<div>` inside my livewire component file. I have tried adding `wire:key` to my element, still not worked. :thinking:

**Comment by chirumist** [comment]
i have same issue and i am remove vue app element 
// new Vue({
//     store,
//     el: "#app",
// });
and work fine

**Comment by wilburpowery** [comment]
Install this package with npm or Yarn, import it and you should be good to go. It worked out of the box for me.

https://github.com/livewire/vue

**Comment by mblarsen** [comment]
I'm experiencing this when an input is invalid. Typing normally works fine and the model is synced, but when say the input is too short (`min:5`) and a validation error is returned it loses focus.

**Comment by roitto** [comment]
This might be an answer that should be posted into the livewire/vue repo, but I found the reason why my inputs were losing focus even if the livewire-vue scripts were correctly included after livewire tags.

My app.js assets was missing `window.Vue = require('vue');` Because i don't like to include stuff in to the "global object."

And the livewire-vue tries to access property from that window.Vue object: https://github.com/livewire/vue/blob/master/src/index.js#L27 

So i did this:
```
import Vue from 'vue';
window.Vue = Vue;
```
to fix this issue.

**Comment by Algeneralo** [comment]
Hi All,
I'm having the same issue with my side, but I don't have any Vue on that page
anyone can help?

**Comment by danpalmieri** [comment]
Has anyone solved this bug?

**Comment by danpalmieri** [comment]
> Install this package with npm or Yarn, import it and you should be good to go. It worked out of the box for me.
> 
> https://github.com/livewire/vue

This worked me out of the box as well!

**Comment by Algeneralo** [comment]
> > Install this package with npm or Yarn, import it and you should be good to go. It worked out of the box for me.
> > https://github.com/livewire/vue
> 
> This worked for me out of the box as well!

Unfortunately, I don't use vue on that page

**Comment by wilburpowery** [comment]
> > > Install this package with npm or Yarn, import it and you should be good to go. It worked out of the box for me.
> > > https://github.com/livewire/vue
> > 
> > 
> > This worked for me out of the box as well!
> 
> Unfortunately, I don't use vue on that page

You don't have any Vue components on that page or you don't have ANY empty Vue instance wrapped around like `div#app` or something similar?

**Comment by Algeneralo** [comment]
@wilburpowery 
I don't have any Vue instance there

**Comment by mokhosh** [comment]
Same issue. Don't have Vue in the project.

BUT I have a session flash message, and when I don't flash the message, this doesn't happen:

**Comment by VexxZeroZero** [comment]
I have the same problem and I did not include Vue in my project.

**Comment by ssarljames** [comment]
I have the same issue.

This is my temporary work around instead of

`wire:model="name"`

I use

`wire:change="$set('name', $event.target.value)"`

This approach only update the model when focus lose on the form control.

**Comment by bicibg** [comment]
Ok, i have the same problem but I have no nested components, no Vue components, no fancy stuff, Only a blade template with model binding and a controller that emits an event. I tried to go through the troubleshooting guide in the documentation but nothing is helping. I thought i share my code as it seems like one of the simplest ones shared in this issue.

Things I tried:
-  Adding wire:key="{{ some unique key }}" to pretty much all components first one by one, then some combination of them like the main wrapper element, input element...etc
- Using @livewire to inject, using <livewire:some-component to inject
- adding key() (when using @livewire()) or :key (when using <livewire:) whilst injecting the livewire component
- removed all clutter and left only html code
- removed all relevant JS code

**recipe-search.blade.php** => This template is the one causing problem. After the first request, input losing focus. Afterwards focus stays

`<div class="row justify-content-center w-100">
    <div class="col-md-6">
        <div class="search-box">
            <input type="text" class="form-control" wire:model="searchTerm">
        </div>
    </div>
</div>`

**RecipeSearch.php**
`<?php

namespace App\Http\Livewire;

use Livewire\Component;

class RecipeSearch extends Component
{

    public $searchTerm = '';

    public function render()
    {
        $searchTerm = '%' . $this->searchTerm . '%';
        $this->emit('searchTerm', $searchTerm);
        return view('livewire.recipe-search');
    }
}
`
**index.blde.php** (This is where the component is injected)
`@extends('layouts.app')

@section('content')
    <div class="container pt-5">
        @livewire('recipe-search')
        @livewire('recipes')
    </div>
@endsection`

**What DID work** (But this is hardly the solution). Removing all but main wrapper element and the input element from the blade template
`<div class="col-md-6">
    <input type="text" class="form-control" wire:model="searchTerm">
</div>`

**Comment by nuernbergerA** [comment]
@samoraa and @bicibg I've tried to reproduce your issues but with the provided code it worked for me.

Could you post a code example to reproduce the issue without domain specifics?

**Comment by bicibg** [comment]
Will do asap

**Comment by bicibg** [comment]
@nuernbergerA @calebporzio 
I prepared a code for you with the isolated code for demonstration. When you open the page you will see 2 identical input boxes. One loses focus, one doesn't. They are labeled accordingly.

**Clean demo code (Laravel project)** 
- https://github.com/bicibg/livewire-755.git

**Files to work with:**
- resources/views/livewire/search.blade.php
- app/Http/Livewire/Search.php

**Findings**
 - I have built the livewire for development environment to see which lifecycle hooks are. It looks like for the input which loses focus, the node is being discarded, readded and losing focus. For the input which does not lose focus, the node does not get discarded. 
 - I have also noticed a lag whilst typing into the input which does not lose focus, if you type fast enough some letters are lost in between requests.

- I'll keep posted if I find anything else. May I create a PR if I can a find/fix? 

**DEMO**
Here is a gif of how it looks:

![Peek 2020-06-28 02-05](https://user-images.githubusercontent.com/7289441/85934693-f7f15a80-b8e6-11ea-92ee-9c1cfb02d913.gif)

**Comment by nuernbergerA** [comment]
@bicibg do you use `vue` in your project?

**Comment by bicibg** [comment]
In my original code yes. In demo project, no

**Comment by nuernbergerA** [comment]
@bicibg https://github.com/livewire/vue should fix your problems.

**Comment by calebporzio** [comment]
@bicibg, I've also copy and pasted your code exactly (with the nested divs) and everything worked perfectly.

Outside of having Vue installed, the only thing I can think of would be that because you are emitting an event in your render method, another component is listening for it and doing something with focus when it here's it, therefore robbing the focus from this element. That wouldn't explain why the nesting and not nesting changes this.

For all other issues, here's a way to think about these problems.

An input element losing focus is a symptom of two things:
* A third-party JS lib messing with the DOM: Vue, some other lib like a date-picker
* A Dom-diffing issue with Livewire itself (these are caused when the tool Livewire uses to diff/patch: morphdom, looses track of what elements are the same and which are different.). You can read more about these issues here: https://laravel-livewire.com/docs/troubleshooting

It's getting hard to keep track of things inside this issue.

I'm going to close this one.

The original problem that spawned this issue is  likely solved by installing the livewire/vue plugin for better Vue support.

The latter one mentioned has not been able to be reproduced.

Please re-submit issues that still persist with domain-agnostic code that is stripped of all styling and extraneous bahavior/markup.

Thanks!

**Comment by bicibg** [comment]
Thanks. I actually tried the troubleshooting doca to no avail. in the demo project I posted there were no libraries installed apart from laravel/ui. Also no event emitting. But I'll still dig a bit more see if I can find anything on my own.

**Comment by Icrmsoftware** [comment]
Maybe this will help you.

https://laravel-livewire.com/docs/properties#lazy-updating

By default, Livewire sends a request to the server after every input event (or change in some cases). This is usually fine for things like <select> elements that don't typically fire rapid updates, however, this is often unnecessary for text fields that update as the user types.

In those cases, use the lazy directive modifier to listen for the native "change" event.

<input type="text" wire:model.lazy="search">

Now, the $search property will only be updated when the user clicks away from the input field.

**Comment by iAmKevinMcKee** [comment]
I'm getting the same issue, but only on one component. I've tried a bunch of things as well. I completely removed Vue. I took out some datepicker inputs. Still no luck figuring out what's causing this.

I have other components on the page where I don't lose focus on the first request. If I can figure this out I will post an update here.

**Comment by iAmKevinMcKee** [comment]
Okay, I am getting some idea of why this is happening for me. For some reason when the page is loaded, my inputs are not inside the form. After the first Livewire update, everything gets moved inside the form. Still have no idea why, but at least I'm a step closer.

Before Livewire Update (form is closed -- no idea why)
![image](https://user-images.githubusercontent.com/4503765/88359312-d04faf80-cd37-11ea-8502-c485ab441f98.png)

After Livewire Update (all my inputs are inside the form now, like they should be)
![image](https://user-images.githubusercontent.com/4503765/88359324-de9dcb80-cd37-11ea-9ac1-b31ea47f06c5.png)

Livewire Blade Template (showing the form is not closed)
![image](https://user-images.githubusercontent.com/4503765/88359357-f6754f80-cd37-11ea-819c-e8fb0c913bbd.png)

**Comment by edwinheij** [comment]
My HTML wasn’t good. Forgot to close a tag. Maybe that will help you.

Op 24 jul. 2020 om 05:59 heeft Kevin McKee <notifications@github.com> het volgende geschreven:

﻿

Okay, I am getting some idea of why this is happening for me. For some reason when the page is loaded, my inputs are not inside the form. After the first Livewire update, everything gets moved inside the form. Still have no idea why, but at least I'm a step closer.

Before Livewire Update (form is closed -- no idea why)
[image]<https://user-images.githubusercontent.com/4503765/88359312-d04faf80-cd37-11ea-8502-c485ab441f98.png>

After Livewire Update (all my inputs are inside the form now, like they should be)
[image]<https://user-images.githubusercontent.com/4503765/88359324-de9dcb80-cd37-11ea-9ac1-b31ea47f06c5.png>

Livewire Blade Template (showing the form is not closed)
[image]<https://user-images.githubusercontent.com/4503765/88359357-f6754f80-cd37-11ea-819c-e8fb0c913bbd.png>

**Comment by alfonsobries** [comment]
Just my two cents on this issue, I spent hours in a similar error without luck until I think it was just a bug on livewire and tried an alternative solution.

Turned out that the problem was on my side because in the project we had a middleware that was minifying the HTML of the view, that was probably changing the HTML enough to livewire decide to "override" the content on the first request.

**Comment by moazam1** [comment]
In my case, I copied my form from another blade file and it had old('xxx') and name attribute. I removed both from all fields and it worked for me.

**Comment by vovayatsyuk** [comment]
Had the same issue. Fixed by removing not used input with "id" name:

```html
<form wire:submit.prevent="save">
    <input type="hidden" name="id" value=".."/> <!-- remove this field, or change its name to fix the issue -->
    ...
</form>
```

**Comment by therealseeku** [comment]
Same issue here without VUE Code

In our case we use Cloudflare as Proxy and Loadbalancer.

Our solution was to disable Minification of JS with a pagerule.
Hope this helps somebody.

**Comment by recycledbeans** [comment]
I was having a similar issue and my issue was related to what @edwinheij mentioned. I had an open anchor tag that, once closed, resolved the issue.

**Comment by KenDeocs** [comment]
If you are using jquery with live wire try to put this code below your <script src="jquery.js"></script> 

<script>
    var $j = jQuery.noConflict();
<script>

this helps me to remove conflict with jquery and livewire.

**Comment by KenDeocs** [comment]
If you are using jquery with live wire try to put this code below your <script src="jquery.js"></script>.

`<script> var $j = jQuery.noConflict(); <script>`

 this helps me to remove conflict with jquery and livewire.

**Comment by bahiaxip** [comment]
I had similar issue under modals bootstrap. Create modal worked correctly but Edit modal lost the focus, I resolved removing forms tag: <form> and </form>. Worked!. Hope can be useful

**Comment by lilessam** [comment]
That solution is what worked for me, I had `id="name"` on the input that I didn't need, when removed the issue is gone!

> Had the same issue. Fixed by removing not used input with "id" name:
> 
> ```
> <form wire:submit.prevent="save">
>     <input type=".." name="id" value=".."/> 
>     ...
> </form>
> ```

**Comment by AmodD** [comment]
just make sure the input field is not within a form or table tag
